language: go
go:
- stable
script:
- go get ./...
- make all
deploy:
  provider: releases
  api_key:
    secure: vtvvMeLyzgT5vPEbzBjA9ZsFI9vYLjjMRuRmojv5kXG+RGaZrPvBXu4Cys/IPB71yYpNXEEiLHP5mSb+rxWXMs7pH9FUuWfxV6yEBkPqR61EcSPQBQ4bame05zCgbRUgSeeF+z5nk9V86+XbFC86RGanwuaw2asCGbFxBlpKHSqWyCXw1YHwLS4Nyf2TDDEPrCG0z4WkIxvJQqU/H6814meb+2yL22dktua/bD5R9GLkqrCSXav7lZwmiyKCuYncIgM41asYFZLtlDk0r2V3b1wVvfRjOX1GawOPEoOkKB814JsLQqjOC8sQ84j46SaihsHVs8O8eFxMhEInx/Ak5TJHGy7pQ4HcZqNCqnYskzwjzAlfFGXXXgAw9hInmAaqaFDsz+CLvkicNqh7WOP1dWKjeZde67zXS9BNVtcNIU+YM56rFKz5CYDe0YFW+5sE34woCxfqcYeoY7ibH59TnRUeV2VS1GPzLpt4K+Y2uE8HNYa2bfO25KQ5U2f/zOXYmyApqOHv0vTJTb/ZS1K/pQxLr7GKmhITj4UfdBRxJ/l676rbvvrecfEe0d5hxwAxF9RUNEyed9v9IURDvb+aknjPL8wMPZTYmtp7QWErXN3rry/7JkObtS+7qGy1nNaZEwnghO4+0PcaQVg/dOPkL85ZHWxLxyffxotCVFju6/U=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
    repo: halkeye/git-version-commits
